# Generated by Django 2.2.9 on 2020-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kesif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesifNo', models.CharField(max_length=120, verbose_name='Kesif_No')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('musteri', models.CharField(max_length=250, verbose_name='Musteri')),
                ('ilgiliKisi', models.CharField(max_length=100, verbose_name='İlgili_Kisi')),
                ('tel', models.CharField(max_length=12, verbose_name='Telefon')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('aciklama', models.TextField(verbose_name='Aciklama')),
            ],
        ),
    ]
