# Generated by Django 2.2.9 on 2020-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesif', '0002_auto_20200204_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='tarih',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
