# Generated by Django 2.2.9 on 2020-02-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesif', '0003_auto_20200204_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='ilgiliKisi',
            field=models.CharField(max_length=100, verbose_name='İlgili Kisi'),
        ),
        migrations.AlterField(
            model_name='kesif',
            name='kesifNo',
            field=models.CharField(max_length=120, verbose_name='Kesif No'),
        ),
    ]
