# Generated by Django 2.2.9 on 2020-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesif', '0004_auto_20200204_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='tarih',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
    ]
