# Generated by Django 2.2.9 on 2020-02-04 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kesif', '0005_auto_20200204_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='tarih',
            field=models.DateField(default=datetime.datetime(2020, 2, 4, 20, 32, 41, 915925, tzinfo=utc), verbose_name='Tarih'),
        ),
    ]
