# Generated by Django 2.2.9 on 2020-02-06 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kesif', '0006_auto_20200204_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='tarih',
            field=models.DateField(default=datetime.datetime(2020, 2, 6, 12, 18, 44, 426001, tzinfo=utc), null=True, verbose_name='Tarih'),
        ),
    ]
